WIP: InsertionPageType on prepareForLogging\rTESTING=unit
promotedai/promoted-ts-client pull request #28
Opened 2021-06-22 02:42 UTC by scottmcmaster

@danbosnichill would you mind double-checking the logic and (especially) the names of things before I add tests? Thanks!

2021-06-22 03:14 UTC, danbosnichill reviewed
The logic looks good to me.

2021-06-22 15:20 UTC, scottmcmaster commented
> The logic looks good to me.

Thanks, I added a couple of tests and took off the "WIP", feel free to have a final look.

2021-06-23 18:40 UTC, danbosnichill requested changes

2021-06-23 18:40 UTC, danbosnichill commented on src/client.ts
> +      if (this.shadowTrafficDeliveryPercent > 0 && metricsRequest.insertionPageType != InsertionPageType.Unpaged) {
Depending on which paging value is set, it'd impact:
1. the offset used when calculating `position`.
2. which page to take from unpaged when trimming to a page.

2021-06-23 18:54 UTC, scottmcmaster commented on src/client.ts
> +      if (this.shadowTrafficDeliveryPercent > 0 && metricsRequest.insertionPageType != InsertionPageType.Unpaged) {
We use the paging parameters for that currently. Are you saying that we'd override that somehow, and/or change the behavior when it's not provided (and how?)?

That's somewhat orthogonal to shadow traffic, though, right? At any rate it's in a different part of the code.

2021-07-14 20:57 UTC, scottmcmaster commented on README.md
> +## Pagination
@danbosnichill please review, thanks!

2021-07-14 20:58 UTC, scottmcmaster commented on src/client.ts
> +      if (this.shadowTrafficDeliveryPercent > 0 && metricsRequest.insertionPageType != InsertionPageType.Unpaged) {
I modified the logic in applyPaging per our discuss, please double-check.

2021-07-15 05:22 UTC, danbosnichill requested changes

2021-07-15 05:22 UTC, danbosnichill commented on README.md
> +  - When `insertionPageType` is "pre-paged", the SDK assumes the client is handling paging, and the position offset is assumed to be 0.
Maybe rephrase this case.  `offset` should still be set.  The SDK won't paginate.

2021-07-15 05:22 UTC, danbosnichill commented on src/client.ts
> +      // "unpaged"...but if you set it, it had best not be "prepaged".
As we talked about in person, I like your recommendation about breaking down the input counts so this is harder to screw up.  If this isn't feasible, we might want to force the parameter on `deliver` too (to lower the chance of errors).

2021-07-15 05:22 UTC, danbosnichill commented on src/client.ts
> +    if (insertionPageType === InsertionPageType.PrePaged) {
I think lines 407-414 are messed up.   If it's unpaged and we're running delivery in this client, we'll to do an offset into the list of insertions before producing a page.

2021-07-15 15:43 UTC, scottmcmaster commented on src/client.ts
> +      // "unpaged"...but if you set it, it had best not be "prepaged".
The counts breakdown, we might want to make sure we've covered all the cases and review the proposal, then follow up on that in a subsequent PR.

For "forcing" in the current approach, are you talking about changing this code so that it treats "unset" as an error case rather than assuming unpaged, and/or going beyond the current "call handleError if performChecks" all the way to "raise an exception and stop the flow"?

2021-07-15 21:10 UTC, scottmcmaster reviewed
After some refactoring and our discussions, I think the approach as realized in code is more principled now, please double-check one more time, thanks :-).

2021-07-15 21:10 UTC, scottmcmaster commented on src/client.ts
> +    if (insertionPageType === InsertionPageType.PrePaged) {
Done in paging.ts.

2021-07-17 01:39 UTC, danbosnichill commented on src/pager.ts
> +    insertionPageType?: InsertionPageType
Might be better to force the SDK-internal methods to set it.

2021-07-17 01:39 UTC, danbosnichill commented on src/pager.ts
> +        insertion.position = start;
Something seems off.  It looks like index and start are equal in this loop.  

I think the PrePaged case is broken.  By be easier to read if you rename 'start' to something like 'startOffset'.

```
    let offset = paging?.offset ?? 0;
    let index = offset;
    if (insertionPageType === InsertionPageType.PrePaged) {
      // When insertions are pre-paged, we ignore any provided offset.
      index = 0;
    }

    let size = paging?.size ?? -1;
    if (size <= 0) {
      size = insertions.length;
    }

    const insertionPage: Insertion[] = [];
    while (index < insertions.length && insertionPage.length < size) {
      const insertion = insertions[index];
      if (assignPosition) {
        insertion.position = offset;
      }
      insertionPage.push(insertion);
      index++;
      offset++;
    }

    return insertionPage;
```

2021-07-17 01:39 UTC, danbosnichill commented on src/pager.ts
> +  applyPaging = (
Might make sense to have a unit test just for applyPaging.

2021-07-17 19:38 UTC, scottmcmaster commented on src/pager.ts
> +        insertion.position = start;
It worked like I intended, which means I'm still confused about what we are trying to accomplish with position assignment during paging :-(. For now I will just change to your code.

2021-07-17 19:38 UTC, scottmcmaster commented on src/client.ts
> +    const insertion = new Pager().applyPaging(fullInsertion, false, request?.paging, metricsRequest.insertionPageType);
> This is cleaner.
> 
> Not for this PR - I think splitting and naming the different types of insertions (fullInsertion, requestInsertion, responseInsertion) differently might help.

I think if I were to try to do that in this PR, it would mess everything up, so I'd prefer to defer that.

2021-07-17 19:38 UTC, scottmcmaster commented on src/client.ts
> +    const insertion = new Pager().applyPaging(fullInsertion, false, request?.paging, metricsRequest.insertionPageType);
> Please add a comment for when assignPosition should be false vs true.
> 
> I'm a little worried we're now not assigning position on the responseInsertions that are actually logged. It looks like we aren't when skimming the code.
> 
> I think it's fine to move the responseInsertion applyPaging logic to only happen inside prepareForLogging/deliver (and not in the deferred createLogRequestFn). I originally did that as an optimization.

I think it's this comment that's already there (?): "which deliver requests do and log requests may not"

2021-07-17 19:38 UTC, scottmcmaster commented on src/client.ts
> +    const insertion = new Pager().applyPaging(fullInsertion, false, request?.paging, metricsRequest.insertionPageType);
> Please add a comment for when assignPosition should be false vs true.
> 
> I'm a little worried we're now not assigning position on the responseInsertions that are actually logged. It looks like we aren't when skimming the code.
> 
> I think it's fine to move the responseInsertion applyPaging logic to only happen inside prepareForLogging/deliver (and not in the deferred createLogRequestFn). I originally did that as an optimization.

It seems difficult to do that without a bigger redo of the structure, since the paged insertions need to go on the log request, but the log request doesn't exist until the deferred function gets called.

I thought we didn't want position on log-only requests for, I'm not sure why actually. What do you think about changing applyPaging to assign position if and only if it's not already set? I think that would solve a lot of confusion.

2021-07-17 19:38 UTC, scottmcmaster commented on src/pager.ts
> +  applyPaging = (
I will wait for replies to some of the other questions first, but yes.

2021-07-18 06:09 UTC, danbosnichill commented on src/client.ts
> +    const insertion = new Pager().applyPaging(fullInsertion, false, request?.paging, metricsRequest.insertionPageType);
> I think if I were to try to do that in this PR, it would mess everything up, so I'd prefer to defer that.

Yea.  Not for this PR.

> but the log request doesn't exist until the deferred function gets called.

It's fine to change this.

> What do you think about changing applyPaging to assign position if and only if it's not already set? I think that would solve a lot of confusion.

I'm open to that if we only applyPaging on responseInsertions.

2021-07-18 06:22 UTC, danbosnichill commented on src/pager.ts
> +   * @param insertions the full set of insertions
`LogRequest.insertion` are responseInsertions.

In the upcoming synthetic DeliveryLog work, I'll stick them on `DeliveryLog.response.insertion`.

2021-07-18 06:22 UTC, danbosnichill commented on src/pager.ts
> +    insertionPageType?: InsertionPageType
`insertionPageType: InsertionPageType` then make the callers convert from undefined.

2021-07-19 15:17 UTC, scottmcmaster commented on src/pager.ts
> +    insertionPageType?: InsertionPageType
Ok, it's a required field here as well as (necessarily) on the request types now.

2021-07-19 17:48 UTC, scottmcmaster commented on src/client.test.ts
>            requestId: 'uuid0',
My tentative change to always assign position if undefined in applyPaging would fix this.

2021-07-20 05:12 UTC, danbosnichill approved these changes

2021-07-20 05:12 UTC, danbosnichill commented on src/pager.ts
> +      insertionPage.push(insertion);
perf nit - when we do perf optimization, we should avoid push and set the array size directly.

This perf test isn't accurate since it runs locally.
https://jsbench.me/rbkrblk7jr/1

2021-07-20 16:43 UTC, scottmcmaster commented on src/client.ts
> +      // "unpaged"...but if you set it, it had best not be "prepaged".
The field/parameter is required now on the request types.

2021-07-20 17:18 UTC, scottmcmaster commented on src/pager.ts
> +      insertionPage.push(insertion);
I just did it.

2021-07-20 17:18 UTC, scottmcmaster commented on src/client.test.ts
> +      const expectedInsertions = toResponseInsertions([newProduct('2')]);
In this case, I think the extra line emphasizes the purpose of the test.

2021-07-20 17:18 UTC, scottmcmaster commented on src/client.test.ts
> +          position: 0,
I think this change is correct -- it's SDK-delivery-provided positions. Maybe clarify why you weren't expecting that here in that case because I might be missing something.

2021-07-20 17:18 UTC, scottmcmaster commented on src/client.test.ts
> +      // Should not have position set due to the custom compact function we're testing with.
This is a case I mentioned yesterday: Because compaction runs post-apply-paging, if the SDK client gives us a compaction function that strips position, we don't have any control over it...(?)

2021-07-20 17:18 UTC, scottmcmaster commented on src/client.test.ts
> +          toInsertionOnlyContentId(newProduct('3')),
This has to do with the reply to a comment I made below.

2021-07-21 19:48 UTC, danbosnichill commented on src/client.test.ts
> +      // Should not have position set due to the custom compact function we're testing with.
Ah, yea.  Currently, if they have a bad compact function, we break.

One idea is to change compact to only impact properties.

2021-07-21 19:53 UTC, danbosnichill approved these changes
I only skimmed the updates.  GitHub does a horrible job showing diffs.  It isn't comparing against the last commit I reviewed.  :-(

2021-07-21 19:53 UTC, danbosnichill commented on src/client.test.ts
> +          position: 0,
Yes, this is correct.  I'm just complaining about GitHub.

2021-07-21 19:53 UTC, danbosnichill commented on src/client.test.ts
> +          toInsertionOnlyContentId(newProduct('3')),
Got it.  Yea, we don't want clients to be able to remove these fields.  The test is correct but the client call is bad.

Longer-term, we should probably change compact to just impact properties.

2021-07-21 22:06 UTC, scottmcmaster commented on src/pager.ts
> +  applyPaging = (
Did this.

2021-07-21 22:07 UTC, scottmcmaster commented on src/client.test.ts
> +          toInsertionOnlyContentId(newProduct('3')),
Per our discussion, I opened an issue for this in the backlog.

2021-07-21 22:08 UTC, scottmcmaster commented on src/client.test.ts
> +      // Should not have position set due to the custom compact function we're testing with.
Per our discussion, issue opened in the backlog.

2021-07-21 22:09 UTC, merged